
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelVacio
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelVacio
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelVacio";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
