
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class MouseTestDialog
	{
		private global::Gtk.VBox dialog1_VBox;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Image image1;

		private global::Gtk.Label labelInfo;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Fixed fixedPane;

		private global::Gtk.Button buttonClickMe;

		private global::Gtk.HButtonBox __gtksharp_73_Stetic_TopLevelDialog_ActionArea;

		private global::Gtk.Button button386;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Alignment alignment3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.MouseTestDialog
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.MouseTestDialog";
			// Container child pesco.MouseTestDialog.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox ();
			this.dialog1_VBox.Name = "dialog1_VBox";
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.dialog1_VBox.Add (this.alignment1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox[this.alignment1]));
			w1.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			this.hbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment4]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 1000;
			this.vbox2.HeightRequest = 600;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.BorderWidth = ((uint)(6));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Ypad = 6;
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.raton.png");
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.WidthRequest = 800;
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.Xalign = 0f;
			this.labelInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("¡Hola!\nAntes de comenzar vamos a hacer una prueba de ratón. \nDebes pulsar varias veces sobre el botón <b>¡Púlsame!</b>. \nSi tienes problemas, consulta con el dinamizador.");
			this.labelInfo.UseMarkup = true;
			this.hbox1.Add (this.labelInfo);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelInfo]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(9));
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixedPane = new global::Gtk.Fixed ();
			this.fixedPane.Name = "fixedPane";
			this.fixedPane.HasWindow = false;
			// Container child fixedPane.Gtk.Fixed+FixedChild
			this.buttonClickMe = new global::Gtk.Button ();
			this.buttonClickMe.CanFocus = true;
			this.buttonClickMe.Name = "buttonClickMe";
			this.buttonClickMe.UseUnderline = true;
			this.buttonClickMe.Label = global::Mono.Unix.Catalog.GetString ("¡Pulsame!");
			this.fixedPane.Add (this.buttonClickMe);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixedPane[this.buttonClickMe]));
			w8.X = 423;
			w8.Y = 66;
			this.vbox3.Add (this.fixedPane);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixedPane]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea = new global::Gtk.HButtonBox ();
			this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea.Name = "__gtksharp_73_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_73_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button386 = new global::Gtk.Button ();
			this.button386.CanFocus = true;
			this.button386.Name = "button386";
			this.button386.UseUnderline = true;
			this.button386.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea.Add (this.button386);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea[this.button386]));
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.__gtksharp_73_Stetic_TopLevelDialog_ActionArea]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment5.Name = "alignment5";
			this.hbox2.Add (this.alignment5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment5]));
			w14.Position = 2;
			this.dialog1_VBox.Add (this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox[this.hbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.dialog1_VBox.Add (this.alignment3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox[this.alignment3]));
			w16.Position = 2;
			this.Add (this.dialog1_VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonClickMe.Clicked += new global::System.EventHandler (this.buttonPulsameCallback);
			this.buttonClickMe.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnButtonClickMeKeyPressEvent);
		}
	}
}
