
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class CheckMicrofone
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Image imagepepe;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Label explanation;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Table table3;

		private global::Gtk.Label labelP1;

		private global::Gtk.Label labelP11;

		private global::Gtk.Label labelP2;

		private global::Gtk.Label labelP22;

		private global::Gtk.Label labelP3;

		private global::Gtk.Label labelP33;

		private global::Gtk.Button playButton;

		private global::Gtk.Image imagebtn3;

		private global::Gtk.Button recordButton;

		private global::Gtk.Image imagebtn1;

		private global::Gtk.Button stopButton;

		private global::Gtk.Image imagebtn2;

		private global::Gtk.Alignment alignment14;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.HBox hboxP4;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Label label6;

		private global::Gtk.HBox hboxButton;

		private global::Gtk.ToggleButton togglebutton1;

		private global::Gtk.ToggleButton togglebutton2;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.HBox hboxP5;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Label labelP5;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Button buttonStartExercise;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.CheckMicrofone
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.CheckMicrofone";
			// Container child pesco.CheckMicrofone.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment3]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.WidthRequest = 1250;
			this.frame1.HeightRequest = 660;
			this.frame1.Name = "frame1";
			this.frame1.LabelYalign = 0f;
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			// Container child hbox4.Gtk.Box+BoxChild
			this.imagepepe = new global::Gtk.Image ();
			this.imagepepe.Name = "imagepepe";
			this.hbox4.Add (this.imagepepe);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.imagepepe]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(23));
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big><b>¿Funciona correctamente el micrófono?</b></big></big></big></big>");
			this.label3.UseMarkup = true;
			this.label3.UseUnderline = true;
			this.label3.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(2));
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment15.Name = "alignment15";
			this.vbox5.Add (this.alignment15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment15]));
			w5.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.explanation = new global::Gtk.Label ();
			this.explanation.WidthRequest = 1000;
			this.explanation.Name = "explanation";
			this.explanation.Xpad = 100;
			this.explanation.Yalign = 1f;
			this.explanation.LabelProp = global::Mono.Unix.Catalog.GetString ("\n<big><big><big>Para comprobar el correcto funcionamiento del micrófono siga los\nsiguientes pasos:</big></big></big>");
			this.explanation.UseMarkup = true;
			this.explanation.Wrap = true;
			this.vbox5.Add (this.explanation);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.explanation]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w7.Position = 1;
			w7.Padding = ((uint)(10));
			this.hbox4.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.UseMarkup = true;
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment13.Name = "alignment13";
			this.hbox2.Add (this.alignment13);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment13]));
			w12.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(40));
			// Container child table3.Gtk.Table+TableChild
			this.labelP1 = new global::Gtk.Label ();
			this.labelP1.Name = "labelP1";
			this.labelP1.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><b>Paso 1.</b></big></big></big>");
			this.labelP1.UseMarkup = true;
			this.table3.Add (this.labelP1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP1]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelP11 = new global::Gtk.Label ();
			this.labelP11.Name = "labelP11";
			this.labelP11.Xalign = 0f;
			this.labelP11.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big>Pulse<b> Comenzar Grabación</b> y hable\npara grabar su voz.</big></big></big>");
			this.labelP11.UseMarkup = true;
			this.table3.Add (this.labelP11);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP11]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelP2 = new global::Gtk.Label ();
			this.labelP2.Sensitive = false;
			this.labelP2.Name = "labelP2";
			this.labelP2.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><b>Paso 2:</b></big></big></big>");
			this.labelP2.UseMarkup = true;
			this.table3.Add (this.labelP2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP2]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelP22 = new global::Gtk.Label ();
			this.labelP22.Sensitive = false;
			this.labelP22.Name = "labelP22";
			this.labelP22.Xalign = 0f;
			this.labelP22.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big>Pulse <b>Parar Grabación</b>, cuando termine\nde hablar.</big></big></big>");
			this.labelP22.UseMarkup = true;
			this.table3.Add (this.labelP22);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP22]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelP3 = new global::Gtk.Label ();
			this.labelP3.Sensitive = false;
			this.labelP3.Name = "labelP3";
			this.labelP3.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><b>Paso 3:</b></big></big></big>");
			this.labelP3.UseMarkup = true;
			this.table3.Add (this.labelP3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP3]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelP33 = new global::Gtk.Label ();
			this.labelP33.Sensitive = false;
			this.labelP33.Name = "labelP33";
			this.labelP33.Xalign = 0f;
			this.labelP33.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big>Pulse <b>Escuchar grabación</b> para oir su voz.</big></big></big>");
			this.labelP33.UseMarkup = true;
			this.table3.Add (this.labelP33);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3[this.labelP33]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.playButton = new global::Gtk.Button ();
			this.playButton.Sensitive = false;
			this.playButton.CanFocus = true;
			this.playButton.Name = "playButton";
			// Container child playButton.Gtk.Container+ContainerChild
			this.imagebtn3 = new global::Gtk.Image ();
			this.imagebtn3.Name = "imagebtn3";
			this.playButton.Add (this.imagebtn3);
			this.playButton.Label = null;
			this.table3.Add (this.playButton);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.playButton]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.recordButton = new global::Gtk.Button ();
			this.recordButton.CanFocus = true;
			this.recordButton.Name = "recordButton";
			// Container child recordButton.Gtk.Container+ContainerChild
			this.imagebtn1 = new global::Gtk.Image ();
			this.imagebtn1.Name = "imagebtn1";
			this.recordButton.Add (this.imagebtn1);
			this.recordButton.Label = null;
			this.table3.Add (this.recordButton);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3[this.recordButton]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.stopButton = new global::Gtk.Button ();
			this.stopButton.Sensitive = false;
			this.stopButton.CanFocus = true;
			this.stopButton.Name = "stopButton";
			// Container child stopButton.Gtk.Container+ContainerChild
			this.imagebtn2 = new global::Gtk.Image ();
			this.imagebtn2.Name = "imagebtn2";
			this.stopButton.Add (this.imagebtn2);
			this.stopButton.Label = null;
			this.table3.Add (this.stopButton);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3[this.stopButton]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.table3]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment14.Name = "alignment14";
			this.hbox2.Add (this.alignment14);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment14]));
			w26.Position = 2;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w27.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.hboxP4 = new global::Gtk.HBox ();
			this.hboxP4.Name = "hboxP4";
			this.hboxP4.Spacing = 6;
			this.hboxP4.BorderWidth = ((uint)(20));
			// Container child hboxP4.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.hboxP4.Add (this.alignment1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hboxP4[this.alignment1]));
			w28.Position = 0;
			// Container child hboxP4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Ypad = 21;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"blue\"><big><big><big><b>¿Ha escuchado correctamente el sonido grabado?</b></big></big></big></span>");
			this.label6.UseMarkup = true;
			this.hboxP4.Add (this.label6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hboxP4[this.label6]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hboxP4.Gtk.Box+BoxChild
			this.hboxButton = new global::Gtk.HBox ();
			this.hboxButton.Name = "hboxButton";
			this.hboxButton.Spacing = 6;
			// Container child hboxButton.Gtk.Box+BoxChild
			this.togglebutton1 = new global::Gtk.ToggleButton ();
			this.togglebutton1.WidthRequest = 125;
			this.togglebutton1.CanFocus = true;
			this.togglebutton1.Name = "togglebutton1";
			this.togglebutton1.UseUnderline = true;
			this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("SI");
			this.hboxButton.Add (this.togglebutton1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxButton[this.togglebutton1]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hboxButton.Gtk.Box+BoxChild
			this.togglebutton2 = new global::Gtk.ToggleButton ();
			this.togglebutton2.WidthRequest = 125;
			this.togglebutton2.CanFocus = true;
			this.togglebutton2.Name = "togglebutton2";
			this.togglebutton2.UseUnderline = true;
			this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString ("NO");
			this.hboxButton.Add (this.togglebutton2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hboxButton[this.togglebutton2]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.hboxP4.Add (this.hboxButton);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hboxP4[this.hboxButton]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hboxP4.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment6.Name = "alignment6";
			this.hboxP4.Add (this.alignment6);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hboxP4[this.alignment6]));
			w33.Position = 3;
			this.alignment10.Add (this.hboxP4);
			this.vbox1.Add (this.alignment10);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment10]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxP5 = new global::Gtk.HBox ();
			this.hboxP5.Name = "hboxP5";
			this.hboxP5.Spacing = 6;
			this.hboxP5.BorderWidth = ((uint)(20));
			// Container child hboxP5.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment7.Name = "alignment7";
			this.hboxP5.Add (this.alignment7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hboxP5[this.alignment7]));
			w36.Position = 0;
			// Container child hboxP5.Gtk.Box+BoxChild
			this.labelP5 = new global::Gtk.Label ();
			this.labelP5.Name = "labelP5";
			this.labelP5.LabelProp = global::Mono.Unix.Catalog.GetString ("labelP5");
			this.labelP5.UseMarkup = true;
			this.hboxP5.Add (this.labelP5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hboxP5[this.labelP5]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hboxP5.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment11.Name = "alignment11";
			this.hboxP5.Add (this.alignment11);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hboxP5[this.alignment11]));
			w38.Position = 2;
			this.vbox1.Add (this.hboxP5);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxP5]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox3.Add (this.vbox1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox1]));
			w40.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment12.Name = "alignment12";
			this.vbox3.Add (this.alignment12);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment12]));
			w41.Position = 3;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment9.Name = "alignment9";
			this.hbox8.Add (this.alignment9);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment9]));
			w42.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonStartExercise = new global::Gtk.Button ();
			this.buttonStartExercise.Sensitive = false;
			this.buttonStartExercise.CanFocus = true;
			this.buttonStartExercise.Name = "buttonStartExercise";
			this.buttonStartExercise.UseUnderline = true;
			// Container child buttonStartExercise.Gtk.Container+ContainerChild
			global::Gtk.Alignment w43 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w44 = new global::Gtk.HBox ();
			w44.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w45 = new global::Gtk.Image ();
			w45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w44.Add (w45);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w47 = new global::Gtk.Label ();
			w47.LabelProp = global::Mono.Unix.Catalog.GetString ("Comenzar ejercicio");
			w47.UseUnderline = true;
			w44.Add (w47);
			w43.Add (w44);
			this.buttonStartExercise.Add (w43);
			this.hbox8.Add (this.buttonStartExercise);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonStartExercise]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
			w52.Position = 4;
			w52.Expand = false;
			w52.Fill = false;
			this.GtkAlignment.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment);
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
			w55.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment4]));
			w56.Position = 2;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment5.Name = "alignment5";
			this.hbox1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment5]));
			w58.Position = 3;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hboxP4.Hide ();
			this.hboxP5.Hide ();
			this.Hide ();
			this.stopButton.Clicked += new global::System.EventHandler (this.OnStopButtonClicked);
			this.recordButton.Clicked += new global::System.EventHandler (this.OnRecordButtonClicked);
			this.playButton.Clicked += new global::System.EventHandler (this.OnPlayButtonClicked);
			this.togglebutton1.Clicked += new global::System.EventHandler (this.OnTogglebutton1Clicked);
			this.togglebutton2.Clicked += new global::System.EventHandler (this.OnTogglebutton2Clicked);
			this.buttonStartExercise.Clicked += new global::System.EventHandler (this.OnButtonStartExerciseClicked);
		}
	}
}
