
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class TotalPodiumPanel
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.HBox hboxCentral;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Image imageBackground;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Button buttonOK;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Alignment alignment13;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.TotalPodiumPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.TotalPodiumPanel";
			// Container child pesco.TotalPodiumPanel.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment12.Name = "alignment12";
			this.vbox4.Add (this.alignment12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.alignment12]));
			w1.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hboxCentral = new global::Gtk.HBox ();
			this.hboxCentral.Name = "hboxCentral";
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment8.Name = "alignment8";
			this.hboxCentral.Add (this.alignment8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxCentral[this.alignment8]));
			w2.Position = 0;
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.WidthRequest = 1000;
			this.imageBackground.HeightRequest = 600;
			this.imageBackground.Name = "imageBackground";
			this.vbox2.Add (this.imageBackground);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.imageBackground]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment6.Name = "alignment6";
			this.hbox2.Add (this.alignment6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment6]));
			w4.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			// Container child buttonOK.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.buttonOK.Add (w5);
			this.hbox2.Add (this.buttonOK);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonOK]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hboxCentral.Add (this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxCentral[this.vbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment7.Name = "alignment7";
			this.hboxCentral.Add (this.alignment7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxCentral[this.alignment7]));
			w16.Position = 2;
			this.vbox4.Add (this.hboxCentral);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hboxCentral]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment13.Name = "alignment13";
			this.vbox4.Add (this.alignment13);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.alignment13]));
			w18.Position = 2;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonOK.Clicked += new global::System.EventHandler (this.OnButtonOKClicked);
		}
	}
}
