
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelDirectNumbers
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignmentLeft;

		private global::Gtk.VBox vboxCentral;

		private global::Gtk.Alignment alignmentTop;

		private global::Gtk.Fixed fixedBlackboard;

		private global::Gtk.Image image2631;

		private global::Gtk.Label labelNumero;

		private global::Gtk.Table tableButtons;

		private global::Gtk.Button buttonDelete;

		private global::Gtk.Button buttonNumber;

		private global::Gtk.Button buttonNumber1;

		private global::Gtk.Button buttonNumber2;

		private global::Gtk.Button buttonNumber3;

		private global::Gtk.Button buttonNumber4;

		private global::Gtk.Button buttonNumber5;

		private global::Gtk.Button buttonNumber6;

		private global::Gtk.Button buttonNumber7;

		private global::Gtk.Button buttonNumber8;

		private global::Gtk.Button buttonNumber9;

		private global::Gtk.VBox vboxReady;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Label labelNewSequence;

		private global::Gtk.Label labelPressIAmReady;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Button buttonReady;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Alignment alignmentBottom;

		private global::Gtk.Alignment alignmentRight;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelDirectNumbers
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelDirectNumbers";
			// Container child pesco.PanelDirectNumbers.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignmentLeft = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentLeft.Name = "alignmentLeft";
			this.hbox2.Add (this.alignmentLeft);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignmentLeft]));
			w1.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxCentral = new global::Gtk.VBox ();
			this.vboxCentral.Name = "vboxCentral";
			this.vboxCentral.Spacing = 6;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.alignmentTop = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentTop.Name = "alignmentTop";
			this.vboxCentral.Add (this.alignmentTop);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxCentral[this.alignmentTop]));
			w2.Position = 0;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.fixedBlackboard = new global::Gtk.Fixed ();
			this.fixedBlackboard.Name = "fixedBlackboard";
			this.fixedBlackboard.HasWindow = false;
			// Container child fixedBlackboard.Gtk.Fixed+FixedChild
			this.image2631 = new global::Gtk.Image ();
			this.image2631.WidthRequest = 474;
			this.image2631.HeightRequest = 334;
			this.image2631.Name = "image2631";
			this.image2631.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.DigitosDirectos.img.blackboard.png");
			this.fixedBlackboard.Add (this.image2631);
			// Container child fixedBlackboard.Gtk.Fixed+FixedChild
			this.labelNumero = new global::Gtk.Label ();
			this.labelNumero.WidthRequest = 474;
			this.labelNumero.HeightRequest = 334;
			this.labelNumero.Name = "labelNumero";
			this.labelNumero.UseMarkup = true;
			this.labelNumero.Justify = ((global::Gtk.Justification)(2));
			this.fixedBlackboard.Add (this.labelNumero);
			this.vboxCentral.Add (this.fixedBlackboard);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxCentral[this.fixedBlackboard]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.tableButtons = new global::Gtk.Table (((uint)(4)), ((uint)(3)), true);
			this.tableButtons.Name = "tableButtons";
			this.tableButtons.RowSpacing = ((uint)(6));
			this.tableButtons.ColumnSpacing = ((uint)(6));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonDelete = new global::Gtk.Button ();
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.Label = global::Mono.Unix.Catalog.GetString ("Borrar");
			this.tableButtons.Add (this.buttonDelete);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonDelete]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber = new global::Gtk.Button ();
			this.buttonNumber.CanFocus = true;
			this.buttonNumber.Name = "buttonNumber";
			this.buttonNumber.UseUnderline = true;
			this.buttonNumber.Label = global::Mono.Unix.Catalog.GetString ("0");
			this.tableButtons.Add (this.buttonNumber);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber1 = new global::Gtk.Button ();
			this.buttonNumber1.CanFocus = true;
			this.buttonNumber1.Name = "buttonNumber1";
			this.buttonNumber1.UseUnderline = true;
			this.buttonNumber1.Label = global::Mono.Unix.Catalog.GetString ("1");
			this.tableButtons.Add (this.buttonNumber1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber1]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber2 = new global::Gtk.Button ();
			this.buttonNumber2.CanFocus = true;
			this.buttonNumber2.Name = "buttonNumber2";
			this.buttonNumber2.UseUnderline = true;
			this.buttonNumber2.Label = global::Mono.Unix.Catalog.GetString ("2");
			this.tableButtons.Add (this.buttonNumber2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber2]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber3 = new global::Gtk.Button ();
			this.buttonNumber3.CanFocus = true;
			this.buttonNumber3.Name = "buttonNumber3";
			this.buttonNumber3.UseUnderline = true;
			this.buttonNumber3.Label = global::Mono.Unix.Catalog.GetString ("3");
			this.tableButtons.Add (this.buttonNumber3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber3]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber4 = new global::Gtk.Button ();
			this.buttonNumber4.CanFocus = true;
			this.buttonNumber4.Name = "buttonNumber4";
			this.buttonNumber4.UseUnderline = true;
			this.buttonNumber4.Label = global::Mono.Unix.Catalog.GetString ("4");
			this.tableButtons.Add (this.buttonNumber4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber4]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber5 = new global::Gtk.Button ();
			this.buttonNumber5.CanFocus = true;
			this.buttonNumber5.Name = "buttonNumber5";
			this.buttonNumber5.UseUnderline = true;
			this.buttonNumber5.Label = global::Mono.Unix.Catalog.GetString ("5");
			this.tableButtons.Add (this.buttonNumber5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber5]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber6 = new global::Gtk.Button ();
			this.buttonNumber6.CanFocus = true;
			this.buttonNumber6.Name = "buttonNumber6";
			this.buttonNumber6.UseUnderline = true;
			this.buttonNumber6.Label = global::Mono.Unix.Catalog.GetString ("6");
			this.tableButtons.Add (this.buttonNumber6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber6]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber7 = new global::Gtk.Button ();
			this.buttonNumber7.CanFocus = true;
			this.buttonNumber7.Name = "buttonNumber7";
			this.buttonNumber7.UseUnderline = true;
			this.buttonNumber7.Label = global::Mono.Unix.Catalog.GetString ("7");
			this.tableButtons.Add (this.buttonNumber7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber7]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber8 = new global::Gtk.Button ();
			this.buttonNumber8.CanFocus = true;
			this.buttonNumber8.Name = "buttonNumber8";
			this.buttonNumber8.UseUnderline = true;
			this.buttonNumber8.Label = global::Mono.Unix.Catalog.GetString ("8");
			this.tableButtons.Add (this.buttonNumber8);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber8]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableButtons.Gtk.Table+TableChild
			this.buttonNumber9 = new global::Gtk.Button ();
			this.buttonNumber9.CanFocus = true;
			this.buttonNumber9.Name = "buttonNumber9";
			this.buttonNumber9.UseUnderline = true;
			this.buttonNumber9.Label = global::Mono.Unix.Catalog.GetString ("9");
			this.tableButtons.Add (this.buttonNumber9);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableButtons[this.buttonNumber9]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxCentral.Add (this.tableButtons);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxCentral[this.tableButtons]));
			w17.Position = 2;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.vboxReady = new global::Gtk.VBox ();
			this.vboxReady.Name = "vboxReady";
			this.vboxReady.Spacing = 6;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment6.Name = "alignment6";
			this.vboxReady.Add (this.alignment6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.alignment6]));
			w18.Position = 0;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.labelNewSequence = new global::Gtk.Label ();
			this.labelNewSequence.Name = "labelNewSequence";
			this.labelNewSequence.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_desc=\"Ahafoni CLM Bold 36\" color=\"blue\">Ahora una nueva secuencia de números</span>");
			this.labelNewSequence.UseMarkup = true;
			this.vboxReady.Add (this.labelNewSequence);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.labelNewSequence]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.labelPressIAmReady = new global::Gtk.Label ();
			this.labelPressIAmReady.Name = "labelPressIAmReady";
			this.labelPressIAmReady.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_desc=\"Ahafoni CLM Bold 36\" color=\"blue\">¡Pulsa el botón <span color=\"black\">Estoy listo</span>!</span>");
			this.labelPressIAmReady.UseMarkup = true;
			this.vboxReady.Add (this.labelPressIAmReady);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.labelPressIAmReady]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.vboxReady.Add (this.alignment1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.alignment1]));
			w21.Position = 3;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.hbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment2]));
			w22.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonReady = new global::Gtk.Button ();
			this.buttonReady.CanFocus = true;
			this.buttonReady.Name = "buttonReady";
			this.buttonReady.UseUnderline = true;
			this.buttonReady.Label = global::Mono.Unix.Catalog.GetString ("Estoy listo");
			this.hbox1.Add (this.buttonReady);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonReady]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment3]));
			w24.Position = 2;
			this.vboxReady.Add (this.hbox1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.hbox1]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vboxReady.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment7.Name = "alignment7";
			this.vboxReady.Add (this.alignment7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxReady[this.alignment7]));
			w26.Position = 5;
			this.vboxCentral.Add (this.vboxReady);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vboxCentral[this.vboxReady]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.alignmentBottom = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentBottom.Name = "alignmentBottom";
			this.vboxCentral.Add (this.alignmentBottom);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vboxCentral[this.alignmentBottom]));
			w28.Position = 4;
			this.hbox2.Add (this.vboxCentral);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vboxCentral]));
			w29.Position = 1;
			w29.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignmentRight = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentRight.Name = "alignmentRight";
			this.hbox2.Add (this.alignmentRight);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignmentRight]));
			w30.Position = 2;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonNumber9.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber8.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber7.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber6.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber5.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber4.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber3.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber2.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber1.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonNumber.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonDelete.Clicked += new global::System.EventHandler (this.numberButtonClicked);
			this.buttonReady.Clicked += new global::System.EventHandler (this.buttonReadyClicked);
		}
	}
}
