
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class SpatialReasoningPanel
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Alignment alignment20;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Alignment alignment18;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image imagepepe;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label1;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Label explanation;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HBox cajaMuestras;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HBox cajaOpciones;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox cajaBotones;

		private global::Gtk.Alignment alignment21;

		private global::Gtk.Button botonListo;

		private global::Gtk.Alignment alignment19;

		private global::Gtk.Alignment alignment17;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.SpatialReasoningPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.SpatialReasoningPanel";
			// Container child pesco.SpatialReasoningPanel.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 1200;
			this.vbox2.HeightRequest = 660;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment20 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment20.Name = "alignment20";
			this.vbox2.Add (this.alignment20);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment20]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment18.Name = "alignment18";
			this.hbox7.Add (this.alignment18);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment18]));
			w2.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.WidthRequest = 1250;
			this.frame5.HeightRequest = 660;
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame5.LabelYalign = 0f;
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.imagepepe = new global::Gtk.Image ();
			this.imagepepe.Name = "imagepepe";
			this.imagepepe.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.resources.img.reasoning.pepehabla.gif");
			this.hbox2.Add (this.imagepepe);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.imagepepe]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big>¿Qué dos fragmentos no pertenecen a la imagen?</big></big></big></big>");
			this.label1.UseMarkup = true;
			this.label1.UseUnderline = true;
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(50));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.explanation = new global::Gtk.Label ();
			this.explanation.WidthRequest = 1000;
			this.explanation.HeightRequest = 75;
			this.explanation.Name = "explanation";
			this.explanation.UseMarkup = true;
			this.explanation.Wrap = true;
			this.alignment3.Add (this.explanation);
			this.vbox3.Add (this.alignment3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox7.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox7.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.cajaMuestras = new global::Gtk.HBox ();
			this.cajaMuestras.HeightRequest = 0;
			this.cajaMuestras.Name = "cajaMuestras";
			this.cajaMuestras.Spacing = 6;
			this.vbox7.Add (this.cajaMuestras);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.cajaMuestras]));
			w10.Position = 2;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox7.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator3]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.cajaOpciones = new global::Gtk.HBox ();
			this.cajaOpciones.WidthRequest = 200;
			this.cajaOpciones.Name = "cajaOpciones";
			this.cajaOpciones.Spacing = 6;
			this.vbox7.Add (this.cajaOpciones);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.cajaOpciones]));
			w12.Position = 4;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox7.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator1]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.cajaBotones = new global::Gtk.HBox ();
			this.cajaBotones.Name = "cajaBotones";
			this.cajaBotones.Spacing = 6;
			// Container child cajaBotones.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment21.Name = "alignment21";
			this.cajaBotones.Add (this.alignment21);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.cajaBotones[this.alignment21]));
			w14.Position = 0;
			// Container child cajaBotones.Gtk.Box+BoxChild
			this.botonListo = new global::Gtk.Button ();
			this.botonListo.CanFocus = true;
			this.botonListo.Name = "botonListo";
			this.botonListo.UseUnderline = true;
			// Container child botonListo.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dialog);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("¡Listo!");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.botonListo.Add (w15);
			this.cajaBotones.Add (this.botonListo);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.cajaBotones[this.botonListo]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox7.Add (this.cajaBotones);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.cajaBotones]));
			w24.Position = 6;
			w24.Expand = false;
			w24.Fill = false;
			this.GtkAlignment1.Add (this.vbox7);
			this.frame5.Add (this.GtkAlignment1);
			this.hbox7.Add (this.frame5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.frame5]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment19.Name = "alignment19";
			this.hbox7.Add (this.alignment19);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment19]));
			w28.Position = 2;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
			w29.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment17.Name = "alignment17";
			this.vbox2.Add (this.alignment17);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment17]));
			w30.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
