
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class SeriesPlaceholder
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Image image6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.SeriesPlaceholder
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.SeriesPlaceholder";
			// Container child pesco.SeriesPlaceholder.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.Reasoning.LogicalSeries.figures.placeholder.png");
			this.vbox2.Add (this.image6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
