
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class ReasoningInstructionDialog
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Image image5;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image image6;

		private global::Gtk.Label labelPauseText;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox10;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.Image image7;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Image image8;

		private global::Gtk.Label label2;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Image image11;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox11;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Image image9;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Image image10;

		private global::Gtk.Label labelPauseText2;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Button button6;

		private global::Gtk.Button button25;

		private global::Gtk.Button button26;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.ReasoningInstructionDialog
			this.Name = "pesco.ReasoningInstructionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child pesco.ReasoningInstructionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment9.Name = "alignment9";
			this.vbox6.Add (this.alignment9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment9]));
			w2.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.abuelo2.png");
			this.vbox6.Add (this.image5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.image5]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox9.Add (this.vbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.Reasoning.gui.dialog2.png");
			this.fixed2.Add (this.image6);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelPauseText = new global::Gtk.Label ();
			this.labelPauseText.WidthRequest = 810;
			this.labelPauseText.HeightRequest = 189;
			this.labelPauseText.Name = "labelPauseText";
			this.labelPauseText.Xalign = 0f;
			this.labelPauseText.UseMarkup = true;
			this.labelPauseText.Wrap = true;
			this.fixed2.Add (this.labelPauseText);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.labelPauseText]));
			w6.X = 78;
			w6.Y = 59;
			this.hbox9.Add (this.fixed2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox9]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox3.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator3]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w10.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment10.Name = "alignment10";
			this.vbox7.Add (this.alignment10);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment10]));
			w11.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.abuelo2.png");
			this.vbox7.Add (this.image7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.image7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox10.Add (this.vbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.Reasoning.gui.dialog2.png");
			this.fixed3.Add (this.image8);
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 810;
			this.label2.HeightRequest = 196;
			this.label2.Name = "label2";
			this.label2.Xalign = 0f;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("\n");
			this.label2.UseMarkup = true;
			this.label2.Wrap = true;
			this.fixed3.Add (this.label2);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
			w15.X = 77;
			w15.Y = 55;
			this.hbox10.Add (this.fixed3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.fixed3]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox4.Add (this.hbox10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox10]));
			w17.Position = 0;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox4.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.vbox4.Add (this.image11);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image11]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
			w20.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment11.Name = "alignment11";
			this.vbox8.Add (this.alignment11);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment11]));
			w21.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.abuelo2.png");
			this.vbox8.Add (this.image9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.image9]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox11.Add (this.vbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.Reasoning.gui.dialog2.png");
			this.fixed4.Add (this.image10);
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.labelPauseText2 = new global::Gtk.Label ();
			this.labelPauseText2.WidthRequest = 786;
			this.labelPauseText2.HeightRequest = 189;
			this.labelPauseText2.Name = "labelPauseText2";
			this.labelPauseText2.Xalign = 0f;
			this.labelPauseText2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color='blue'><big><big><big>Para empezar con el ejercicio pulsa el botón <span color='black'>Aceptar</span></big></big></big></span>");
			this.labelPauseText2.UseMarkup = true;
			this.labelPauseText2.Wrap = true;
			this.fixed4.Add (this.labelPauseText2);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.labelPauseText2]));
			w25.X = 119;
			w25.Y = 60;
			this.hbox11.Add (this.fixed4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.fixed4]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox5.Add (this.hbox11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox11]));
			w27.Position = 0;
			w27.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox5.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator2]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
			w29.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w30.Position = 0;
			// Internal child pesco.ReasoningInstructionDialog.ActionArea
			global::Gtk.HButtonBox w31 = this.ActionArea;
			w31.Name = "dialog1_ActionArea";
			w31.Spacing = 10;
			w31.BorderWidth = ((uint)(5));
			w31.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			// Container child button6.Gtk.Container+ContainerChild
			global::Gtk.Alignment w32 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w33 = new global::Gtk.HBox ();
			w33.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Dialog);
			w33.Add (w34);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w36 = new global::Gtk.Label ();
			w36.LabelProp = global::Mono.Unix.Catalog.GetString ("Anterior");
			w36.UseUnderline = true;
			w33.Add (w36);
			w32.Add (w33);
			this.button6.Add (w32);
			w31.Add (this.button6);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.button6]));
			w40.Expand = false;
			w40.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button25 = new global::Gtk.Button ();
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			this.button25.UseUnderline = true;
			// Container child button25.Gtk.Container+ContainerChild
			global::Gtk.Alignment w41 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w42 = new global::Gtk.HBox ();
			w42.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w43 = new global::Gtk.Image ();
			w43.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Dialog);
			w42.Add (w43);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w45 = new global::Gtk.Label ();
			w45.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w45.UseUnderline = true;
			w42.Add (w45);
			w41.Add (w42);
			this.button25.Add (w41);
			w31.Add (this.button25);
			global::Gtk.ButtonBox.ButtonBoxChild w49 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.button25]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button26 = new global::Gtk.Button ();
			this.button26.CanFocus = true;
			this.button26.Name = "button26";
			this.button26.UseUnderline = true;
			// Container child button26.Gtk.Container+ContainerChild
			global::Gtk.Alignment w50 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w51 = new global::Gtk.HBox ();
			w51.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w52 = new global::Gtk.Image ();
			w52.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dialog);
			w51.Add (w52);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w54 = new global::Gtk.Label ();
			w54.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w54.UseUnderline = true;
			w51.Add (w54);
			w50.Add (w51);
			this.button26.Add (w50);
			this.AddActionWidget (this.button26, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.button26]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1198;
			this.DefaultHeight = 1228;
			this.Show ();
		}
	}
}
