
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelVocalesYNumerosIzq2
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image image167;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Alignment alignment16;

		private global::Gtk.Button botonempezarsecuencia;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelVocalesYNumerosIzq2
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelVocalesYNumerosIzq2";
			// Container child pesco.PanelVocalesYNumerosIzq2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.WidthRequest = 1250;
			this.vbox3.HeightRequest = 660;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image167 = new global::Gtk.Image ();
			this.image167.Name = "image167";
			this.image167.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.resources.img.numersvowels.escenario3.jpg");
			this.fixed2.Add (this.image167);
			this.vbox4.Add (this.fixed2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fixed2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment16.Name = "alignment16";
			this.hbox7.Add (this.alignment16);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment16]));
			w3.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.botonempezarsecuencia = new global::Gtk.Button ();
			this.botonempezarsecuencia.CanFocus = true;
			this.botonempezarsecuencia.Name = "botonempezarsecuencia";
			this.botonempezarsecuencia.UseUnderline = true;
			this.botonempezarsecuencia.Label = global::Mono.Unix.Catalog.GetString ("Comenzar Ejercicio");
			this.hbox7.Add (this.botonempezarsecuencia);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.botonempezarsecuencia]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w7.Position = 1;
			w7.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w8.Position = 0;
			w8.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
