
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class FinishSessionPanel
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Image image5;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image image6;

		private global::Gtk.Label label5;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table medalsTable;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Label label10;

		private global::Gtk.Label label6;

		private global::Gtk.Label label9;

		private global::Gtk.Label GtkLabel;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button button7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.FinishSessionPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.FinishSessionPanel";
			// Container child pesco.FinishSessionPanel.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment9.Name = "alignment9";
			this.vbox6.Add (this.alignment9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment9]));
			w1.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.abuelo3.png");
			this.vbox6.Add (this.image5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.image5]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox9.Add (this.vbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.Reasoning.gui.dialog3.png");
			this.fixed2.Add (this.image6);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 786;
			this.label5.HeightRequest = 100;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color='blue'><big><b>¡Enhorabuena!</b></big>\n\nHas completado totalmente esta sesión y has obtenido las siguientes medallas:</span>");
			this.label5.UseMarkup = true;
			this.label5.Wrap = true;
			this.label5.Justify = ((global::Gtk.Justification)(2));
			this.fixed2.Add (this.label5);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
			w5.X = 53;
			w5.Y = 12;
			this.hbox9.Add (this.fixed2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox9]));
			w7.Position = 0;
			w7.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame1.BorderWidth = ((uint)(9));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0.5f, 0f, 0f, 0f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.GtkAlignment.TopPadding = ((uint)(12));
			this.GtkAlignment.RightPadding = ((uint)(12));
			this.GtkAlignment.BottomPadding = ((uint)(12));
			this.GtkAlignment.BorderWidth = ((uint)(21));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.medalsTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.medalsTable.Name = "medalsTable";
			this.medalsTable.RowSpacing = ((uint)(6));
			this.medalsTable.ColumnSpacing = ((uint)(6));
			// Container child medalsTable.Gtk.Table+TableChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.medalsTable.Add (this.alignment2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.medalsTable[this.alignment2]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			// Container child medalsTable.Gtk.Table+TableChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.medalsTable.Add (this.alignment3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.medalsTable[this.alignment3]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			// Container child medalsTable.Gtk.Table+TableChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			this.medalsTable.Add (this.alignment4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.medalsTable[this.alignment4]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			// Container child medalsTable.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1f;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big><b>Bronce</b></big></big></big></big>");
			this.label10.UseMarkup = true;
			this.medalsTable.Add (this.label10);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.medalsTable[this.label10]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			// Container child medalsTable.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1f;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big><b>Oro</b></big></big></big></big>");
			this.label6.UseMarkup = true;
			this.medalsTable.Add (this.label6);
			// Container child medalsTable.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1f;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big><b>Plata</b></big></big></big></big>");
			this.label9.UseMarkup = true;
			this.medalsTable.Add (this.label9);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.medalsTable[this.label9]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			this.GtkAlignment.Add (this.medalsTable);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><big><b>Medallero</b></big></big></big></big>");
			this.GtkLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
			w17.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
			w18.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			// Container child button7.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Dialog);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("Terminar sesión");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.button7.Add (w19);
			this.hbox1.Add (this.button7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button7]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
