
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class GS_PanelCriterias
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Frame frameCentral;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label labelInfo;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Label labelBudget;

		private global::Gtk.Button buttonGoToShops;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.GS_PanelCriterias
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.GS_PanelCriterias";
			// Container child pesco.GS_PanelCriterias.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frameCentral = new global::Gtk.Frame ();
			this.frameCentral.Name = "frameCentral";
			this.frameCentral.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameCentral.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"red\">Tienes que comprarle regalos a las siguientes personas:</span>");
			this.labelInfo.UseMarkup = true;
			this.labelInfo.Wrap = true;
			this.labelInfo.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.labelInfo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelInfo]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.vbox6.Add (this.alignment2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment2]));
			w2.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Homogeneous = true;
			this.vbox5.Spacing = 6;
			this.vbox6.Add (this.vbox5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			this.vbox6.Add (this.alignment3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment3]));
			w4.Position = 3;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelBudget = new global::Gtk.Label ();
			this.labelBudget.Name = "labelBudget";
			this.labelBudget.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.labelBudget);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelBudget]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.GtkAlignment.Add (this.vbox6);
			this.frameCentral.Add (this.GtkAlignment);
			this.vbox3.Add (this.frameCentral);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frameCentral]));
			w8.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonGoToShops = new global::Gtk.Button ();
			this.buttonGoToShops.HeightRequest = 80;
			this.buttonGoToShops.CanFocus = true;
			this.buttonGoToShops.Name = "buttonGoToShops";
			this.buttonGoToShops.UseUnderline = true;
			this.buttonGoToShops.Label = global::Mono.Unix.Catalog.GetString ("Ir a tiendas");
			this.vbox3.Add (this.buttonGoToShops);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.buttonGoToShops]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonGoToShops.Clicked += new global::System.EventHandler (this.GoToShopsCallback);
		}
	}
}
