
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PantallaResultados
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PantallaResultados
			this.Name = "pesco.PantallaResultados";
			this.Title = global::Mono.Unix.Catalog.GetString ("PantallaResultados");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DefaultWidth = 1024;
			this.DefaultHeight = 720;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
