
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelCuentaAtras
	{
		private global::Gtk.Label labelCuentaAtras;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelCuentaAtras
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelCuentaAtras";
			// Container child pesco.PanelCuentaAtras.Gtk.Container+ContainerChild
			this.labelCuentaAtras = new global::Gtk.Label ();
			this.labelCuentaAtras.Name = "labelCuentaAtras";
			this.labelCuentaAtras.Justify = ((global::Gtk.Justification)(2));
			this.Add (this.labelCuentaAtras);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
