
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class ExercisePanelTaskList1
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image imagBack;

		private global::Gtk.Label labelPrevius;

		private global::Gtk.Label label51;

		private global::Gtk.Label labelLevel;

		private global::Gtk.Image imagPepe;

		private global::Gtk.Label label52;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button botonempezarsecuencia;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.ExercisePanelTaskList1
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.ExercisePanelTaskList1";
			// Container child pesco.ExercisePanelTaskList1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.imagBack = new global::Gtk.Image ();
			this.imagBack.WidthRequest = 1024;
			this.imagBack.HeightRequest = 600;
			this.imagBack.Name = "imagBack";
			this.fixed2.Add (this.imagBack);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelPrevius = new global::Gtk.Label ();
			this.labelPrevius.Name = "labelPrevius";
			this.labelPrevius.LabelProp = global::Mono.Unix.Catalog.GetString ("labelPrevius");
			this.labelPrevius.UseMarkup = true;
			this.fixed2.Add (this.labelPrevius);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.labelPrevius]));
			w2.X = 192;
			w2.Y = 118;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label51 = new global::Gtk.Label ();
			this.label51.WidthRequest = 600;
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"blue\"><big><big><big><big><big>Pulsa el botón <span color=\"black\"><b>¡Listo!</b></span>\ny  te mostraré de nuevo los recados.</big></big></big></big></big></span>\n");
			this.label51.UseMarkup = true;
			this.label51.Wrap = true;
			this.fixed2.Add (this.label51);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label51]));
			w3.X = 400;
			w3.Y = 320;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelLevel = new global::Gtk.Label ();
			this.labelLevel.Name = "labelLevel";
			this.labelLevel.LabelProp = global::Mono.Unix.Catalog.GetString ("labelLevel");
			this.fixed2.Add (this.labelLevel);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.labelLevel]));
			w4.X = 355;
			w4.Y = 68;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.imagPepe = new global::Gtk.Image ();
			this.imagPepe.Name = "imagPepe";
			this.fixed2.Add (this.imagPepe);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.imagPepe]));
			w5.X = 7;
			w5.Y = 220;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label52 = new global::Gtk.Label ();
			this.label52.Name = "label52";
			this.label52.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"blue\"><big><big><big><big><big>Pulsa el botón <span color=\"black\"><b>¡Listo!</b></span>\ny te mostraré una lista con\nmás recados.</big></big></big></big></big></span>\n");
			this.label52.UseMarkup = true;
			this.fixed2.Add (this.label52);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label52]));
			w6.X = 499;
			w6.Y = 283;
			this.vbox5.Add (this.fixed2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.fixed2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.hbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment1]));
			w8.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.botonempezarsecuencia = new global::Gtk.Button ();
			this.botonempezarsecuencia.CanFocus = true;
			this.botonempezarsecuencia.Name = "botonempezarsecuencia";
			this.botonempezarsecuencia.UseUnderline = true;
			// Container child botonempezarsecuencia.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("¡Listo!");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.botonempezarsecuencia.Add (w9);
			this.hbox2.Add (this.botonempezarsecuencia);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.botonempezarsecuencia]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w20.Position = 1;
			w20.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w21.Position = 1;
			w21.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
