
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelVocalesYNumerosCen
	{
		private global::Gtk.Table table2;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Image image394;

		private global::Gtk.Label labelCaracter;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelVocalesYNumerosCen
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelVocalesYNumerosCen";
			// Container child pesco.PanelVocalesYNumerosCen.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.table2.Add (this.alignment2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.alignment2]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			this.table2.Add (this.alignment4);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.alignment4]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.alignment6 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment6.Name = "alignment6";
			this.table2.Add (this.alignment6);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.alignment6]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.alignment7 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment7.Name = "alignment7";
			this.table2.Add (this.alignment7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.alignment7]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image394 = new global::Gtk.Image ();
			this.image394.Name = "image394";
			this.image394.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.ejercicios.LetrasYNumeros.blackboard.png");
			this.fixed1.Add (this.image394);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelCaracter = new global::Gtk.Label ();
			this.labelCaracter.WidthRequest = 149;
			this.labelCaracter.HeightRequest = 194;
			this.labelCaracter.Name = "labelCaracter";
			this.labelCaracter.Justify = ((global::Gtk.Justification)(2));
			this.fixed1.Add (this.labelCaracter);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.labelCaracter]));
			w6.X = 170;
			w6.Y = 53;
			this.table2.Add (this.fixed1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.fixed1]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
