
// This file has been generated by the GUI designer. Do not modify.
namespace ecng
{
	public partial class PanelGlobos
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.DrawingArea drawingarea1;

		private global::Gtk.Button buttonPulsar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ecng.PanelGlobos
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ecng.PanelGlobos";
			// Container child ecng.PanelGlobos.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.vbox2.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.drawingarea1]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonPulsar = new global::Gtk.Button ();
			this.buttonPulsar.CanFocus = true;
			this.buttonPulsar.Name = "buttonPulsar";
			this.buttonPulsar.UseUnderline = true;
			this.buttonPulsar.Label = global::Mono.Unix.Catalog.GetString ("¡Pulsar!");
			this.vbox2.Add (this.buttonPulsar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonPulsar]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonPulsar.Clicked += new global::System.EventHandler (this.callbackButtonPulsar);
		}
	}
}
