
// This file has been generated by the GUI designer. Do not modify.
namespace ecng
{
	public partial class PanelDemoGlobos
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button buttonStartExercise;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ecng.PanelDemoGlobos
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ecng.PanelDemoGlobos";
			// Container child ecng.PanelDemoGlobos.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Demo del ejercicio de Globos");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			this.vbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
			w2.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonStartExercise = new global::Gtk.Button ();
			this.buttonStartExercise.CanFocus = true;
			this.buttonStartExercise.Name = "buttonStartExercise";
			this.buttonStartExercise.UseUnderline = true;
			this.buttonStartExercise.Label = global::Mono.Unix.Catalog.GetString ("Comenzar ejercicio");
			this.vbox2.Add (this.buttonStartExercise);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonStartExercise]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonStartExercise.Clicked += new global::System.EventHandler (this.StartExerciseClicked);
		}
	}
}
