
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PodiumPanel
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.HBox hboxCentral;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.VBox vboxCentral;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image imageBackground;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Alignment alignment12;
		private global::Gtk.Button buttonOK;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.Alignment alignment6;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PodiumPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PodiumPanel";
			// Container child pesco.PodiumPanel.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment4]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxCentral = new global::Gtk.HBox ();
			this.hboxCentral.Name = "hboxCentral";
			this.hboxCentral.Spacing = 6;
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hboxCentral.Add (this.alignment8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxCentral [this.alignment8]));
			w2.Position = 0;
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.vboxCentral = new global::Gtk.VBox ();
			this.vboxCentral.HeightRequest = 650;
			this.vboxCentral.Name = "vboxCentral";
			this.vboxCentral.Spacing = 6;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 1000;
			this.fixed2.HeightRequest = 600;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.WidthRequest = 1000;
			this.imageBackground.HeightRequest = 600;
			this.imageBackground.Name = "imageBackground";
			this.fixed2.Add (this.imageBackground);
			this.vboxCentral.Add (this.fixed2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.fixed2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hbox4.Add (this.alignment12);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment12]));
			w5.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			// Container child buttonOK.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w10.UseUnderline = true;
			w7.Add (w10);
			w6.Add (w7);
			this.buttonOK.Add (w6);
			this.hbox4.Add (this.buttonOK);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.buttonOK]));
			w14.Position = 1;
			this.vboxCentral.Add (this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.hbox4]));
			w15.Position = 1;
			this.hboxCentral.Add (this.vboxCentral);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxCentral [this.vboxCentral]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hboxCentral.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hboxCentral.Add (this.alignment9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxCentral [this.alignment9]));
			w17.Position = 2;
			this.vbox2.Add (this.hboxCentral);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hboxCentral]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.vbox2.Add (this.alignment6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment6]));
			w19.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
