
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class LI_HallPanel
	{
		private global::Gtk.EventBox eventboxBackground;
		private global::Gtk.Image imageBackground;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.LI_HallPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.LI_HallPanel";
			// Container child pesco.LI_HallPanel.Gtk.Container+ContainerChild
			this.eventboxBackground = new global::Gtk.EventBox ();
			this.eventboxBackground.WidthRequest = 1100;
			this.eventboxBackground.HeightRequest = 600;
			this.eventboxBackground.Name = "eventboxBackground";
			// Container child eventboxBackground.Gtk.Container+ContainerChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.WidthRequest = 1100;
			this.imageBackground.HeightRequest = 600;
			this.imageBackground.Name = "imageBackground";
			this.eventboxBackground.Add (this.imageBackground);
			this.Add (this.eventboxBackground);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
