
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class SessionScreen
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView panelExplicacion;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button button30;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button button49;
		private global::Gtk.Button button29;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.SessionScreen
			this.Name = "pesco.SessionScreen";
			this.Title = global::Mono.Unix.Catalog.GetString ("PantallaSesiones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child pesco.SessionScreen.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 400;
			this.hpaned1.BorderWidth = ((uint)(6));
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.panelExplicacion = new global::Gtk.TextView ();
			this.panelExplicacion.Buffer.Text = "¡Bienvenido Pepito!\n\nLa actividad que te toca hoy es Memoria. Tienes que intentar recordar la lista de números que te mostramos y luego ordenarlos.\n\n";
			this.panelExplicacion.TooltipMarkup = "Esta es la descripción de la actividad y/o sesión que tienes seleccionada";
			this.panelExplicacion.WidthRequest = 600;
			this.panelExplicacion.CanFocus = true;
			this.panelExplicacion.Name = "panelExplicacion";
			this.panelExplicacion.Editable = false;
			this.panelExplicacion.CursorVisible = false;
			this.panelExplicacion.WrapMode = ((global::Gtk.WrapMode)(3));
			this.panelExplicacion.PixelsAboveLines = 2;
			this.panelExplicacion.PixelsBelowLines = 2;
			this.panelExplicacion.PixelsInsideWrap = 1;
			this.panelExplicacion.LeftMargin = 7;
			this.panelExplicacion.RightMargin = 7;
			this.GtkScrolledWindow1.Add (this.panelExplicacion);
			this.vbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button30 = new global::Gtk.Button ();
			this.button30.TooltipMarkup = "Pincha aquí para que te lean el texto de arriba";
			this.button30.CanFocus = true;
			this.button30.Name = "button30";
			this.button30.UseUnderline = true;
			// Container child button30.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_volume", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Iniciar locución");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.button30.Add (w3);
			this.hbox4.Add (this.button30);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button30]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox4.Add (this.alignment2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment2]));
			w12.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button49 = new global::Gtk.Button ();
			this.button49.TooltipMarkup = "Pincha aquí para ver los resultados de la última actividad";
			this.button49.CanFocus = true;
			this.button49.Name = "button49";
			this.button49.UseUnderline = true;
			// Container child button49.Gtk.Container+ContainerChild
			global::Gtk.Alignment w13 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w14 = new global::Gtk.HBox ();
			w14.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w15 = new global::Gtk.Image ();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_chart-edit-type", global::Gtk.IconSize.Menu);
			w14.Add (w15);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w17 = new global::Gtk.Label ();
			w17.LabelProp = global::Mono.Unix.Catalog.GetString ("Ver Resultados");
			w17.UseUnderline = true;
			w14.Add (w17);
			w13.Add (w14);
			this.button49.Add (w13);
			this.hbox4.Add (this.button49);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button49]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button29 = new global::Gtk.Button ();
			this.button29.TooltipMarkup = "Pincha aquí para iniciar la siguiente actividad";
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			this.button29.UseUnderline = true;
			// Container child button29.Gtk.Container+ContainerChild
			global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w23 = new global::Gtk.HBox ();
			w23.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w23.Add (w24);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.LabelProp = global::Mono.Unix.Catalog.GetString ("Iniciar Actividad");
			w26.UseUnderline = true;
			w23.Add (w26);
			w22.Add (w23);
			this.button29.Add (w22);
			this.hbox4.Add (this.button29);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button29]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.hpaned1.Add (this.vbox4);
			global::Gtk.Paned.PanedChild w32 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox4]));
			w32.Resize = false;
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 819;
			this.DefaultHeight = 443;
			this.Show ();
			this.hpaned1.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button49.Clicked += new global::System.EventHandler (this.OnViewResultsClick);
			this.button29.Clicked += new global::System.EventHandler (this.OnClickStartActivity);
		}
	}
}
