
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class ConfigurationDialog
	{
		private global::Gtk.ScrolledWindow scrolledWindow;
		private global::Gtk.Table configTable;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Button sendDataButton;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.ConfigurationDialog
			this.Name = "pesco.ConfigurationDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Configuración");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child pesco.ConfigurationDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrolledWindow = new global::Gtk.ScrolledWindow ();
			this.scrolledWindow.CanFocus = true;
			this.scrolledWindow.Name = "scrolledWindow";
			this.scrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.configTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.configTable.Name = "configTable";
			this.configTable.RowSpacing = ((uint)(6));
			this.configTable.ColumnSpacing = ((uint)(6));
			w2.Add (this.configTable);
			this.scrolledWindow.Add (w2);
			w1.Add (this.scrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.scrolledWindow]));
			w5.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.sendDataButton = new global::Gtk.Button ();
			this.sendDataButton.CanFocus = true;
			this.sendDataButton.Name = "sendDataButton";
			this.sendDataButton.UseUnderline = true;
			this.sendDataButton.Label = global::Mono.Unix.Catalog.GetString ("Enviar datos de usuario");
			this.hbox1.Add (this.sendDataButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.sendDataButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child pesco.ConfigurationDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-close";
			this.AddActionWidget (this.buttonCancel, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-save";
			this.AddActionWidget (this.buttonOk, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.sendDataButton.Clicked += new global::System.EventHandler (this.OnSendDataButtonClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
