
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class GS_PanelItemsShop
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.Frame frame7;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.VBox vbox;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Table table;
		private global::Gtk.Alignment alignment7;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.GS_PanelItemsShop
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.GS_PanelItemsShop";
			// Container child pesco.GS_PanelItemsShop.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(4));
			this.frame7.BorderWidth = ((uint)(3));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(3));
			this.GtkAlignment.TopPadding = ((uint)(3));
			this.GtkAlignment.RightPadding = ((uint)(3));
			this.GtkAlignment.BottomPadding = ((uint)(3));
			this.GtkAlignment.BorderWidth = ((uint)(3));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox1.Add (this.alignment6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment6]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.vbox.Add (this.alignment5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox [this.alignment5]));
			w2.Position = 0;
			// Container child vbox.Gtk.Box+BoxChild
			this.table = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(6));
			this.vbox.Add (this.table);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox [this.table]));
			w3.Position = 1;
			this.hbox1.Add (this.vbox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox1.Add (this.alignment7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment7]));
			w5.Position = 2;
			this.GtkAlignment.Add (this.hbox1);
			this.frame7.Add (this.GtkAlignment);
			this.vbox7.Add (this.frame7);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.frame7]));
			w8.Position = 0;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
