
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class UsersToggleButton
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.UsersToggleButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.UsersToggleButton";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
