
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelPackageDelivering
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vboxCentral;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.EventBox eventBoxImage;
		private global::Gtk.Image drawingAreaFixed;
		private global::Gtk.HBox hboxGameButtons;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Button buttonFinish;
		private global::Gtk.HBox hboxDemoButtons;
		private global::Gtk.Button buttonGoLast;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Button buttonStartExercise;
		private global::Gtk.Button buttonGoBack;
		private global::Gtk.Button buttonGoForward;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.VBox vboxLateral;
		private global::Gtk.Frame frameVan;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label labelFuel;
		private global::Gtk.Image imageFuel;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label labelInTheVan;
		private global::Gtk.HBox hboxTable;
		private global::Gtk.Label labelVanTop;
		private global::Gtk.Frame frameDeliver;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelToDeliver1;
		private global::Gtk.Label labelToDeliver2;
		private global::Gtk.Label labelToDeliver3;
		private global::Gtk.Label labelToDeliverTop;
		private global::Gtk.Frame framePickUp;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelToPickUp1;
		private global::Gtk.Label labelToPickUp2;
		private global::Gtk.Label labelToPickUp3;
		private global::Gtk.Label labelToPickUpTop;
		private global::Gtk.VBox vboxLateralButtons;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Alignment alignment4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelPackageDelivering
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelPackageDelivering";
			// Container child pesco.PanelPackageDelivering.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
			w2.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vboxCentral = new global::Gtk.VBox ();
			this.vboxCentral.WidthRequest = 1000;
			this.vboxCentral.Name = "vboxCentral";
			this.vboxCentral.Spacing = 2;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 600;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.eventBoxImage = new global::Gtk.EventBox ();
			this.eventBoxImage.WidthRequest = 998;
			this.eventBoxImage.HeightRequest = 600;
			this.eventBoxImage.Name = "eventBoxImage";
			// Container child eventBoxImage.Gtk.Container+ContainerChild
			this.drawingAreaFixed = new global::Gtk.Image ();
			this.drawingAreaFixed.WidthRequest = 998;
			this.drawingAreaFixed.HeightRequest = 600;
			this.drawingAreaFixed.Name = "drawingAreaFixed";
			this.eventBoxImage.Add (this.drawingAreaFixed);
			this.fixed2.Add (this.eventBoxImage);
			this.vboxCentral.Add (this.fixed2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.fixed2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.hboxGameButtons = new global::Gtk.HBox ();
			this.hboxGameButtons.HeightRequest = 50;
			this.hboxGameButtons.Name = "hboxGameButtons";
			this.hboxGameButtons.Spacing = 6;
			// Container child hboxGameButtons.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hboxGameButtons.Add (this.alignment7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxGameButtons [this.alignment7]));
			w6.Position = 0;
			// Container child hboxGameButtons.Gtk.Box+BoxChild
			this.buttonFinish = new global::Gtk.Button ();
			this.buttonFinish.CanFocus = true;
			this.buttonFinish.Name = "buttonFinish";
			this.buttonFinish.UseUnderline = true;
			this.buttonFinish.Label = global::Mono.Unix.Catalog.GetString ("¡He terminado!");
			this.hboxGameButtons.Add (this.buttonFinish);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxGameButtons [this.buttonFinish]));
			w7.Position = 1;
			this.vboxCentral.Add (this.hboxGameButtons);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.hboxGameButtons]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.hboxDemoButtons = new global::Gtk.HBox ();
			this.hboxDemoButtons.HeightRequest = 50;
			this.hboxDemoButtons.Name = "hboxDemoButtons";
			this.hboxDemoButtons.Spacing = 6;
			// Container child hboxDemoButtons.Gtk.Box+BoxChild
			this.buttonGoLast = new global::Gtk.Button ();
			this.buttonGoLast.CanFocus = true;
			this.buttonGoLast.Name = "buttonGoLast";
			this.buttonGoLast.UseUnderline = true;
			// Container child buttonGoLast.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Dnd);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("Saltar instrucciones");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.buttonGoLast.Add (w9);
			this.hboxDemoButtons.Add (this.buttonGoLast);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxDemoButtons [this.buttonGoLast]));
			w17.Position = 0;
			// Container child hboxDemoButtons.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hboxDemoButtons.Add (this.alignment6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxDemoButtons [this.alignment6]));
			w18.Position = 1;
			// Container child hboxDemoButtons.Gtk.Box+BoxChild
			this.buttonStartExercise = new global::Gtk.Button ();
			this.buttonStartExercise.CanFocus = true;
			this.buttonStartExercise.Name = "buttonStartExercise";
			this.buttonStartExercise.UseUnderline = true;
			// Container child buttonStartExercise.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("Comenzar ejercicio");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.buttonStartExercise.Add (w19);
			this.hboxDemoButtons.Add (this.buttonStartExercise);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hboxDemoButtons [this.buttonStartExercise]));
			w27.Position = 2;
			// Container child hboxDemoButtons.Gtk.Box+BoxChild
			this.buttonGoBack = new global::Gtk.Button ();
			this.buttonGoBack.CanFocus = true;
			this.buttonGoBack.Name = "buttonGoBack";
			this.buttonGoBack.UseUnderline = true;
			// Container child buttonGoBack.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Dnd);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w32.LabelProp = global::Mono.Unix.Catalog.GetString ("Anterior");
			w32.UseUnderline = true;
			w29.Add (w32);
			w28.Add (w29);
			this.buttonGoBack.Add (w28);
			this.hboxDemoButtons.Add (this.buttonGoBack);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hboxDemoButtons [this.buttonGoBack]));
			w36.Position = 3;
			// Container child hboxDemoButtons.Gtk.Box+BoxChild
			this.buttonGoForward = new global::Gtk.Button ();
			this.buttonGoForward.CanFocus = true;
			this.buttonGoForward.Name = "buttonGoForward";
			this.buttonGoForward.UseUnderline = true;
			// Container child buttonGoForward.Gtk.Container+ContainerChild
			global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w38 = new global::Gtk.HBox ();
			w38.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Dnd);
			w38.Add (w39);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w41 = new global::Gtk.Label ();
			w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w41.UseUnderline = true;
			w38.Add (w41);
			w37.Add (w38);
			this.buttonGoForward.Add (w37);
			this.hboxDemoButtons.Add (this.buttonGoForward);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hboxDemoButtons [this.buttonGoForward]));
			w45.Position = 4;
			this.vboxCentral.Add (this.hboxDemoButtons);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.hboxDemoButtons]));
			w46.Position = 2;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.vboxCentral.Add (this.alignment9);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.alignment9]));
			w47.Position = 3;
			this.hbox3.Add (this.vboxCentral);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vboxCentral]));
			w48.Position = 1;
			w48.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.vboxLateral = new global::Gtk.VBox ();
			this.vboxLateral.Name = "vboxLateral";
			this.vboxLateral.Spacing = 6;
			// Container child vboxLateral.Gtk.Box+BoxChild
			this.frameVan = new global::Gtk.Frame ();
			this.frameVan.Name = "frameVan";
			this.frameVan.ShadowType = ((global::Gtk.ShadowType)(4));
			// Container child frameVan.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			this.GtkAlignment4.TopPadding = ((uint)(12));
			this.GtkAlignment4.RightPadding = ((uint)(12));
			this.GtkAlignment4.BottomPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelFuel = new global::Gtk.Label ();
			this.labelFuel.Name = "labelFuel";
			this.labelFuel.LabelProp = global::Mono.Unix.Catalog.GetString ("Gasolina:");
			this.labelFuel.UseMarkup = true;
			this.hbox4.Add (this.labelFuel);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelFuel]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.imageFuel = new global::Gtk.Image ();
			this.imageFuel.Name = "imageFuel";
			this.hbox4.Add (this.imageFuel);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.imageFuel]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelInTheVan = new global::Gtk.Label ();
			this.labelInTheVan.Name = "labelInTheVan";
			this.labelInTheVan.LabelProp = global::Mono.Unix.Catalog.GetString ("Llevas:");
			this.hbox5.Add (this.labelInTheVan);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelInTheVan]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hboxTable = new global::Gtk.HBox ();
			this.hboxTable.Name = "hboxTable";
			this.hboxTable.Spacing = 6;
			this.hbox5.Add (this.hboxTable);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hboxTable]));
			w53.Position = 1;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			this.GtkAlignment4.Add (this.vbox6);
			this.frameVan.Add (this.GtkAlignment4);
			this.labelVanTop = new global::Gtk.Label ();
			this.labelVanTop.Name = "labelVanTop";
			this.labelVanTop.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"orange\">Furgoneta</span>");
			this.labelVanTop.UseMarkup = true;
			this.labelVanTop.Justify = ((global::Gtk.Justification)(2));
			this.frameVan.LabelWidget = this.labelVanTop;
			this.vboxLateral.Add (this.frameVan);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vboxLateral [this.frameVan]));
			w57.Position = 0;
			w57.Expand = false;
			// Container child vboxLateral.Gtk.Box+BoxChild
			this.frameDeliver = new global::Gtk.Frame ();
			this.frameDeliver.Name = "frameDeliver";
			this.frameDeliver.ShadowType = ((global::Gtk.ShadowType)(4));
			this.frameDeliver.BorderWidth = ((uint)(1));
			// Container child frameDeliver.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			this.GtkAlignment5.TopPadding = ((uint)(2));
			this.GtkAlignment5.RightPadding = ((uint)(12));
			this.GtkAlignment5.BottomPadding = ((uint)(2));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelToDeliver1 = new global::Gtk.Label ();
			this.labelToDeliver1.WidthRequest = 250;
			this.labelToDeliver1.Name = "labelToDeliver1";
			this.labelToDeliver1.Xalign = 0F;
			this.labelToDeliver1.Wrap = true;
			this.vbox3.Add (this.labelToDeliver1);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelToDeliver1]));
			w58.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelToDeliver2 = new global::Gtk.Label ();
			this.labelToDeliver2.WidthRequest = 250;
			this.labelToDeliver2.Name = "labelToDeliver2";
			this.labelToDeliver2.Xalign = 0F;
			this.labelToDeliver2.Wrap = true;
			this.vbox3.Add (this.labelToDeliver2);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelToDeliver2]));
			w59.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelToDeliver3 = new global::Gtk.Label ();
			this.labelToDeliver3.WidthRequest = 250;
			this.labelToDeliver3.Name = "labelToDeliver3";
			this.labelToDeliver3.Xalign = 0F;
			this.labelToDeliver3.Wrap = true;
			this.vbox3.Add (this.labelToDeliver3);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelToDeliver3]));
			w60.Position = 2;
			this.GtkAlignment5.Add (this.vbox3);
			this.frameDeliver.Add (this.GtkAlignment5);
			this.labelToDeliverTop = new global::Gtk.Label ();
			this.labelToDeliverTop.Name = "labelToDeliverTop";
			this.labelToDeliverTop.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"red\">Cajas para entregar</span>");
			this.labelToDeliverTop.UseMarkup = true;
			this.labelToDeliverTop.Justify = ((global::Gtk.Justification)(2));
			this.frameDeliver.LabelWidget = this.labelToDeliverTop;
			this.vboxLateral.Add (this.frameDeliver);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vboxLateral [this.frameDeliver]));
			w63.Position = 1;
			// Container child vboxLateral.Gtk.Box+BoxChild
			this.framePickUp = new global::Gtk.Frame ();
			this.framePickUp.Name = "framePickUp";
			this.framePickUp.ShadowType = ((global::Gtk.ShadowType)(4));
			this.framePickUp.BorderWidth = ((uint)(1));
			// Container child framePickUp.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			this.GtkAlignment6.TopPadding = ((uint)(2));
			this.GtkAlignment6.RightPadding = ((uint)(12));
			this.GtkAlignment6.BottomPadding = ((uint)(2));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelToPickUp1 = new global::Gtk.Label ();
			this.labelToPickUp1.WidthRequest = 250;
			this.labelToPickUp1.Name = "labelToPickUp1";
			this.labelToPickUp1.Xalign = 0F;
			this.labelToPickUp1.Wrap = true;
			this.vbox4.Add (this.labelToPickUp1);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelToPickUp1]));
			w64.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelToPickUp2 = new global::Gtk.Label ();
			this.labelToPickUp2.WidthRequest = 250;
			this.labelToPickUp2.Name = "labelToPickUp2";
			this.labelToPickUp2.Xalign = 0F;
			this.labelToPickUp2.Wrap = true;
			this.vbox4.Add (this.labelToPickUp2);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelToPickUp2]));
			w65.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelToPickUp3 = new global::Gtk.Label ();
			this.labelToPickUp3.WidthRequest = 250;
			this.labelToPickUp3.Name = "labelToPickUp3";
			this.labelToPickUp3.Xalign = 0F;
			this.labelToPickUp3.Wrap = true;
			this.vbox4.Add (this.labelToPickUp3);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelToPickUp3]));
			w66.Position = 2;
			this.GtkAlignment6.Add (this.vbox4);
			this.framePickUp.Add (this.GtkAlignment6);
			this.labelToPickUpTop = new global::Gtk.Label ();
			this.labelToPickUpTop.Name = "labelToPickUpTop";
			this.labelToPickUpTop.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"blue\">Cajas para recoger</span>");
			this.labelToPickUpTop.UseMarkup = true;
			this.labelToPickUpTop.Justify = ((global::Gtk.Justification)(2));
			this.framePickUp.LabelWidget = this.labelToPickUpTop;
			this.vboxLateral.Add (this.framePickUp);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vboxLateral [this.framePickUp]));
			w69.Position = 2;
			// Container child vboxLateral.Gtk.Box+BoxChild
			this.vboxLateralButtons = new global::Gtk.VBox ();
			this.vboxLateralButtons.Name = "vboxLateralButtons";
			this.vboxLateralButtons.Spacing = 6;
			this.vboxLateral.Add (this.vboxLateralButtons);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vboxLateral [this.vboxLateralButtons]));
			w70.Position = 3;
			// Container child vboxLateral.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.vboxLateral.Add (this.alignment8);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vboxLateral [this.alignment8]));
			w71.Position = 4;
			this.alignment3.Add (this.vboxLateral);
			this.hbox3.Add (this.alignment3);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment3]));
			w73.Position = 2;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment5]));
			w74.Position = 3;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w75.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment4]));
			w76.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonFinish.Clicked += new global::System.EventHandler (this.OnFinishButtonClicked);
			this.buttonGoLast.Clicked += new global::System.EventHandler (this.OnButtonGotoLastClicked);
			this.buttonStartExercise.Clicked += new global::System.EventHandler (this.OnButtonStartExerciseClicked);
			this.buttonGoBack.Clicked += new global::System.EventHandler (this.OnButtonBackwardClicked);
			this.buttonGoForward.Clicked += new global::System.EventHandler (this.GoForward);
		}
	}
}
