
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class DialogPanel
	{
		private global::Gtk.VBox vboxContent;
		private global::Gtk.Image imageBackground;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.DialogPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.DialogPanel";
			// Container child pesco.DialogPanel.Gtk.Container+ContainerChild
			this.vboxContent = new global::Gtk.VBox ();
			this.vboxContent.Name = "vboxContent";
			this.vboxContent.Spacing = 6;
			// Container child vboxContent.Gtk.Box+BoxChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.WidthRequest = 1000;
			this.imageBackground.HeightRequest = 600;
			this.imageBackground.Name = "imageBackground";
			this.vboxContent.Add (this.imageBackground);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxContent [this.imageBackground]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vboxContent);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
