
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelBagItems
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox vboxCentral;
		private global::Gtk.DrawingArea drawingArea;
		private global::Gtk.HBox hboxButtonsDemo;
		private global::Gtk.Button buttonGoLast;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Button buttonGoBack;
		private global::Gtk.Button buttonGoForward;
		private global::Gtk.Button buttonRepeatDemo;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Button buttonStartFinishExercise;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Alignment alignment4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelBagItems
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 1024;
			this.HeightRequest = 600;
			this.Name = "pesco.PanelBagItems";
			// Container child pesco.PanelBagItems.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 1000;
			this.vbox2.HeightRequest = 0;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.vbox2.Add (this.alignment3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment3]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox3.Add (this.alignment2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment2]));
			w2.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vboxCentral = new global::Gtk.VBox ();
			this.vboxCentral.Name = "vboxCentral";
			this.vboxCentral.Spacing = 6;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.drawingArea = new global::Gtk.DrawingArea ();
			this.drawingArea.WidthRequest = 1024;
			this.drawingArea.HeightRequest = 600;
			this.drawingArea.Name = "drawingArea";
			this.vboxCentral.Add (this.drawingArea);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.drawingArea]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.hboxButtonsDemo = new global::Gtk.HBox ();
			this.hboxButtonsDemo.HeightRequest = 50;
			this.hboxButtonsDemo.Name = "hboxButtonsDemo";
			this.hboxButtonsDemo.Spacing = 6;
			// Container child hboxButtonsDemo.Gtk.Box+BoxChild
			this.buttonGoLast = new global::Gtk.Button ();
			this.buttonGoLast.CanFocus = true;
			this.buttonGoLast.Name = "buttonGoLast";
			this.buttonGoLast.UseUnderline = true;
			// Container child buttonGoLast.Gtk.Container+ContainerChild
			global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w5 = new global::Gtk.HBox ();
			w5.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Dnd);
			w5.Add (w6);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w8 = new global::Gtk.Label ();
			w8.LabelProp = global::Mono.Unix.Catalog.GetString ("Saltar instrucciones");
			w8.UseUnderline = true;
			w5.Add (w8);
			w4.Add (w5);
			this.buttonGoLast.Add (w4);
			this.hboxButtonsDemo.Add (this.buttonGoLast);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxButtonsDemo [this.buttonGoLast]));
			w12.Position = 0;
			// Container child hboxButtonsDemo.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			// Container child alignment6.Gtk.Container+ContainerChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment6.Add (this.alignment7);
			this.hboxButtonsDemo.Add (this.alignment6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxButtonsDemo [this.alignment6]));
			w14.Position = 1;
			// Container child hboxButtonsDemo.Gtk.Box+BoxChild
			this.buttonGoBack = new global::Gtk.Button ();
			this.buttonGoBack.CanFocus = true;
			this.buttonGoBack.Name = "buttonGoBack";
			this.buttonGoBack.UseUnderline = true;
			// Container child buttonGoBack.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Dnd);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Anterior");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.buttonGoBack.Add (w15);
			this.hboxButtonsDemo.Add (this.buttonGoBack);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hboxButtonsDemo [this.buttonGoBack]));
			w23.Position = 2;
			// Container child hboxButtonsDemo.Gtk.Box+BoxChild
			this.buttonGoForward = new global::Gtk.Button ();
			this.buttonGoForward.CanFocus = true;
			this.buttonGoForward.Name = "buttonGoForward";
			this.buttonGoForward.UseUnderline = true;
			// Container child buttonGoForward.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Dnd);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.buttonGoForward.Add (w24);
			this.hboxButtonsDemo.Add (this.buttonGoForward);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hboxButtonsDemo [this.buttonGoForward]));
			w32.Position = 3;
			// Container child hboxButtonsDemo.Gtk.Box+BoxChild
			this.buttonRepeatDemo = new global::Gtk.Button ();
			this.buttonRepeatDemo.CanFocus = true;
			this.buttonRepeatDemo.Name = "buttonRepeatDemo";
			this.buttonRepeatDemo.UseUnderline = true;
			this.buttonRepeatDemo.Label = global::Mono.Unix.Catalog.GetString ("Repetir ensayo");
			this.hboxButtonsDemo.Add (this.buttonRepeatDemo);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hboxButtonsDemo [this.buttonRepeatDemo]));
			w33.Position = 4;
			this.vboxCentral.Add (this.hboxButtonsDemo);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.hboxButtonsDemo]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vboxCentral.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w35.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox1.Add (this.alignment8);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment8]));
			w36.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonStartFinishExercise = new global::Gtk.Button ();
			this.buttonStartFinishExercise.CanFocus = true;
			this.buttonStartFinishExercise.Name = "buttonStartFinishExercise";
			this.buttonStartFinishExercise.UseUnderline = true;
			this.buttonStartFinishExercise.Label = global::Mono.Unix.Catalog.GetString ("Iniciar nuevo recorrido");
			this.hbox1.Add (this.buttonStartFinishExercise);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStartFinishExercise]));
			w37.Position = 2;
			this.vboxCentral.Add (this.hbox1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxCentral [this.hbox1]));
			w38.Position = 2;
			w38.Expand = false;
			this.hbox3.Add (this.vboxCentral);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vboxCentral]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment5]));
			w40.Position = 2;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w41.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment4]));
			w42.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonGoLast.Clicked += new global::System.EventHandler (this.OnButtonGoLastClicked);
			this.buttonGoBack.Clicked += new global::System.EventHandler (this.OnButtonBackwardClicked);
			this.buttonGoForward.Clicked += new global::System.EventHandler (this.OnButtonGoForwardClicked);
			this.buttonRepeatDemo.Clicked += new global::System.EventHandler (this.RepeatDemo);
			this.buttonStartFinishExercise.Clicked += new global::System.EventHandler (this.FinishButtonCallback);
		}
	}
}
