
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class VentanaCreditos
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.Image image54;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label2;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HSeparator hseparator2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.VentanaCreditos
			this.Name = "pesco.VentanaCreditos";
			this.Title = global::Mono.Unix.Catalog.GetString ("Acerca de PESCO");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child pesco.VentanaCreditos.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.image54 = new global::Gtk.Image ();
			this.image54.Name = "image54";
			this.image54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("pesco.gui.abuelologo.png");
			this.eventbox1.Add (this.image54);
			this.hbox2.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.eventbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox2.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Plataforma Software para la Estimulación Cognitiva</b>\n\nCopyright (C) 2010 Guadalinfo.es\nCopyright (C) 2010 Consorcio Fernando de los Ríos \ndentro del proyecto Guadalinfo Accesible (Expediente 7/2010) \n\n<b>I. Entidades Participantes:</b>\n\n• Consorcio para el Desarrollo de la Sociedad de la Información y el Conocimiento \"Fernando de los Ríos\"\n• Fundación General Universidad de Granada-Empresa\n\n<b>II. Investigadoras  Principales:</b>\n\nDña. María José Rodríguez Fortiz y Dña. María Visitación Hurtado Torres.\n\n<b>III. Investigadores Colaboradores:</b>\n\n<b>Grupo de Investigación de Neuropsicología y Psiconeuroinmunología Clínicas</b>\n\n• D. Miguel García Pérez\n• D. Alfonso Caracuel Romero\n• Dña. Sandra Santiago Ramajo\n\n<b>Grupo de Informática</b>\n\n• Dña. María Luisa Rodríguez Almendros \n• D. José Luis Garrido Bullejos\n• D. Miguel J. Hornos Barranco\n• D. Manuel Noguera García\n• Dña. Kawtar Benghazi Akhlaki\n• D. Álvaro Fernández López\n• D. Carlos Rodríguez Domínguez \n• Dña. Luz María Roldán Vílchez\n\n<b>IV. Programadores</b>\n\n• D. Álvaro López Martínez\n• Dña. Ana Belén Pelegrina Ortiz\n• Dña. Luz María Roldán Vílchez\n\nColaboración en el diseño del personaje guía de la plataforma PESCO: Dña. Ainhoa Serena Enamorado\n\nReferencia Proyecto: C-3437-00");
			this.label2.UseMarkup = true;
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox1]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 927;
			this.DefaultHeight = 806;
			this.Show ();
		}
	}
}
