
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class GS_PanelSituation
	{
		private global::Gtk.VBox vbox;
		private global::Gtk.HBox hbox;
		private global::Gtk.Label labelTime;
		private global::Gtk.Button buttonViewShoppingList;
		private global::Gtk.Button buttonViewMyShopping;
		private global::Gtk.Button buttonFinishShopping;
		private global::Gtk.Label labelBudget;
		private global::Gtk.Frame frameContent;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vboxContent;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.GS_PanelSituation
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.GS_PanelSituation";
			// Container child pesco.GS_PanelSituation.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			// Container child hbox.Gtk.Box+BoxChild
			this.labelTime = new global::Gtk.Label ();
			this.labelTime.Name = "labelTime";
			this.labelTime.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo");
			this.hbox.Add (this.labelTime);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.labelTime]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonViewShoppingList = new global::Gtk.Button ();
			this.buttonViewShoppingList.CanFocus = true;
			this.buttonViewShoppingList.Name = "buttonViewShoppingList";
			this.buttonViewShoppingList.UseUnderline = true;
			this.buttonViewShoppingList.Label = global::Mono.Unix.Catalog.GetString ("Ver lista de personas y sus gustos");
			this.hbox.Add (this.buttonViewShoppingList);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.buttonViewShoppingList]));
			w2.Position = 1;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonViewMyShopping = new global::Gtk.Button ();
			this.buttonViewMyShopping.CanFocus = true;
			this.buttonViewMyShopping.Name = "buttonViewMyShopping";
			this.buttonViewMyShopping.UseUnderline = true;
			this.buttonViewMyShopping.Label = global::Mono.Unix.Catalog.GetString ("Ver mi compra");
			this.hbox.Add (this.buttonViewMyShopping);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox [this.buttonViewMyShopping]));
			w3.Position = 2;
			// Container child hbox.Gtk.Box+BoxChild
			this.buttonFinishShopping = new global::Gtk.Button ();
			this.buttonFinishShopping.CanFocus = true;
			this.buttonFinishShopping.Name = "buttonFinishShopping";
			this.buttonFinishShopping.UseUnderline = true;
			this.buttonFinishShopping.Label = global::Mono.Unix.Catalog.GetString ("Finalizar compra");
			this.hbox.Add (this.buttonFinishShopping);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox [this.buttonFinishShopping]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.labelBudget = new global::Gtk.Label ();
			this.labelBudget.Name = "labelBudget";
			this.labelBudget.LabelProp = global::Mono.Unix.Catalog.GetString ("Presupuesto");
			this.hbox.Add (this.labelBudget);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox [this.labelBudget]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox.Add (this.hbox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.frameContent = new global::Gtk.Frame ();
			this.frameContent.Name = "frameContent";
			this.frameContent.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameContent.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(2));
			this.GtkAlignment.TopPadding = ((uint)(2));
			this.GtkAlignment.RightPadding = ((uint)(2));
			this.GtkAlignment.BottomPadding = ((uint)(2));
			this.GtkAlignment.BorderWidth = ((uint)(2));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vboxContent = new global::Gtk.VBox ();
			this.vboxContent.Name = "vboxContent";
			this.vboxContent.Spacing = 1;
			this.GtkAlignment.Add (this.vboxContent);
			this.frameContent.Add (this.GtkAlignment);
			this.vbox.Add (this.frameContent);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox [this.frameContent]));
			w9.Position = 1;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonViewShoppingList.Clicked += new global::System.EventHandler (this.ViewShoppingListCallback);
			this.buttonViewMyShopping.Clicked += new global::System.EventHandler (this.ShowMyShoppingCallback);
			this.buttonFinishShopping.Clicked += new global::System.EventHandler (this.FinishShoppingCallback);
		}
	}
}
