
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelDemoPyramidsTest
	{
		private global::Gtk.Table tableTest;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelDemoPyramidsTest
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelDemoPyramidsTest";
			// Container child pesco.PanelDemoPyramidsTest.Gtk.Container+ContainerChild
			this.tableTest = new global::Gtk.Table (((uint)(3)), ((uint)(6)), true);
			this.tableTest.Name = "tableTest";
			this.tableTest.RowSpacing = ((uint)(2));
			this.tableTest.ColumnSpacing = ((uint)(2));
			this.tableTest.BorderWidth = ((uint)(2));
			this.Add (this.tableTest);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
