
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class PanelDemoPyramids
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image imageBackground;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button buttonGoLast;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Button buttonComenzarEjercicio;
		private global::Gtk.Button buttonGoBack;
		private global::Gtk.Button buttonGoForward;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Alignment alignment2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.PanelDemoPyramids
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.PanelDemoPyramids";
			// Container child pesco.PanelDemoPyramids.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.vbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment1]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment3]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 1000;
			this.fixed1.HeightRequest = 600;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.WidthRequest = 1000;
			this.imageBackground.HeightRequest = 599;
			this.imageBackground.Name = "imageBackground";
			this.fixed1.Add (this.imageBackground);
			this.vbox3.Add (this.fixed1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.HeightRequest = 50;
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonGoLast = new global::Gtk.Button ();
			this.buttonGoLast.CanFocus = true;
			this.buttonGoLast.Name = "buttonGoLast";
			this.buttonGoLast.UseUnderline = true;
			// Container child buttonGoLast.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Dnd);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Saltar instrucciones");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.buttonGoLast.Add (w5);
			this.hbox2.Add (this.buttonGoLast);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonGoLast]));
			w13.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
			w14.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonComenzarEjercicio = new global::Gtk.Button ();
			this.buttonComenzarEjercicio.CanFocus = true;
			this.buttonComenzarEjercicio.Name = "buttonComenzarEjercicio";
			this.buttonComenzarEjercicio.UseUnderline = true;
			// Container child buttonComenzarEjercicio.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Comenzar ejercicio");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.buttonComenzarEjercicio.Add (w15);
			this.hbox2.Add (this.buttonComenzarEjercicio);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonComenzarEjercicio]));
			w23.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonGoBack = new global::Gtk.Button ();
			this.buttonGoBack.CanFocus = true;
			this.buttonGoBack.Name = "buttonGoBack";
			this.buttonGoBack.UseUnderline = true;
			// Container child buttonGoBack.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Dnd);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("Anterior");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.buttonGoBack.Add (w24);
			this.hbox2.Add (this.buttonGoBack);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonGoBack]));
			w32.Position = 3;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonGoForward = new global::Gtk.Button ();
			this.buttonGoForward.CanFocus = true;
			this.buttonGoForward.Name = "buttonGoForward";
			this.buttonGoForward.UseUnderline = true;
			// Container child buttonGoForward.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Dnd);
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w37.LabelProp = global::Mono.Unix.Catalog.GetString ("Siguiente");
			w37.UseUnderline = true;
			w34.Add (w37);
			w33.Add (w34);
			this.buttonGoForward.Add (w33);
			this.hbox2.Add (this.buttonGoForward);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonGoForward]));
			w41.Position = 4;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment5]));
			w44.Position = 3;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w46.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonGoLast.Clicked += new global::System.EventHandler (this.OnButtonGoLastClicked);
			this.buttonComenzarEjercicio.Clicked += new global::System.EventHandler (this.comenzarEjercicioClicked);
			this.buttonGoBack.Clicked += new global::System.EventHandler (this.OnButtonGoBackClicked);
			this.buttonGoForward.Clicked += new global::System.EventHandler (this.OnButtonGoForwardClicked);
		}
	}
}
