
// This file has been generated by the GUI designer. Do not modify.
namespace pesco
{
	public partial class ExercisePanelObjectsClassify
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image imagBack;
		private global::Gtk.Label label2;
		private global::Gtk.Image imagPepe;
		private global::Gtk.Label label1;
		private global::Gtk.Label label51;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Button botonempezarsecuencia;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Alignment alignment4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget pesco.ExercisePanelObjectsClassify
			global::Stetic.BinContainer.Attach (this);
			this.Name = "pesco.ExercisePanelObjectsClassify";
			// Container child pesco.ExercisePanelObjectsClassify.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.vbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment5]));
			w1.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox1.Add (this.alignment8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment8]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 1200;
			this.fixed2.HeightRequest = 600;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.imagBack = new global::Gtk.Image ();
			this.imagBack.Name = "imagBack";
			this.fixed2.Add (this.imagBack);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 720;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("labelPrevius");
			this.label2.UseMarkup = true;
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w4.X = 192;
			w4.Y = 118;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.imagPepe = new global::Gtk.Image ();
			this.imagPepe.Name = "imagPepe";
			this.fixed2.Add (this.imagPepe);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.imagPepe]));
			w5.X = 7;
			w5.Y = 220;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 728;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("labelLevel");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.fixed2.Add (this.label1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
			w6.X = 191;
			w6.Y = 59;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label51 = new global::Gtk.Label ();
			this.label51.WidthRequest = 400;
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"blue\"><big><big><big><big><big>Pulsa el botón <span color=\"black\"><b>¡Listo!</b></span>\npara continuar.</big></big></big></big></big></span>\n");
			this.label51.UseMarkup = true;
			this.label51.Wrap = true;
			this.fixed2.Add (this.label51);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label51]));
			w7.X = 334;
			w7.Y = 318;
			this.vbox5.Add (this.fixed2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fixed2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.WidthRequest = 1200;
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox3.Add (this.alignment7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment7]));
			w9.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.botonempezarsecuencia = new global::Gtk.Button ();
			this.botonempezarsecuencia.CanFocus = true;
			this.botonempezarsecuencia.Name = "botonempezarsecuencia";
			this.botonempezarsecuencia.UseUnderline = true;
			// Container child botonempezarsecuencia.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dnd);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("¡Listo!");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.botonempezarsecuencia.Add (w10);
			this.hbox3.Add (this.botonempezarsecuencia);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.botonempezarsecuencia]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox1.Add (this.alignment6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment6]));
			w21.Position = 2;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w22.Position = 1;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox3.Add (this.alignment4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment4]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 2;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
